import React from 'react';

function PolicyContent() {
  return (
    <section className="mt-[20rem] w-full max-w-[1040px] max-md:mt-[18rem]   max-sm:px-4   max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:w-full">
          <div className="grow gap-2.5 py-2.5 text-base text-black  max-md:w-full">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            </p>
            <br />
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            </p>
            <br />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            </p>
          </div>
        </div>
        <div className="flex flex-col w-6/12 max-md:w-full">
          <div className="mt-2.5 text-base text-black max-md:mt-10 max-md:mx-8">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit...
            </p>
            <br />
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore...
            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore...
            </p>
            <br />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...
            <br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default PolicyContent;
